routes/web.php
    Route::post('{reportid}/update', 'ReportController@update')->name('reports.update');
    Route::get('{activity}/export', 'ReportController@export')->name('reports.export');
    Route::get('{activity}/pdfexport', 'ReportController@pdfexport')->name('reports.pdfexport');
    Route::get('assigned_actions', 'ReportController@assignedactivities')->name('reports.assigned_actions');
    Route::post('powerpointexport', 'ReportController@powerpointExport')->name('reports.powerpointexport');
    Route::post('generate_report_export', 'ReportController@generateReportExport')->name('reports.generate_report_export');
    //Route::get('generatepowerpoint', 'ReportController@generatePowerPoint')->name('reports.powerpointgenerate');
    //Route::get('powerpointshow', 'ReportController@powerpointShow')->name('reports.powerpointshow');
    Route::get('generate_report', 'ReportController@generateReport')->name('reports.generate_report');
    Route::get('auditreport', 'ReportController@auditReport')->name('reports.auditreport');
    Route::get('usagereport', 'UsageReportController@index')->name('reports.usage');
    Route::get('productivityreport', 'ProductivityReportController@index')->name('reports.productivity');
    Route::get('sla', 'SLAReportController@index')->name('reports.sla');

});

Route::post('reports/productivityreportajax', 'ProductivityReportController@ajaxCall');

Route::get('assigned_actions/{assignedactionid}/delete/{activityid}', 'ActionsController@deleteAssignedAction')->name('assignedactions.delete');
Route::get('assigned_actions/{assignedactionid}/complete/{activityid}', 'ActionsController@completeAssignedAction')->name('assignedactions.complete');
Route::get('assigned_actions/pdfexport', 'ReportController@assignedactivitiesPdfExport')->name('assignedactions.pdfexport');
Route::get('assigned_actions/export', 'ReportController@assignedactivitiesExport')->name('assignedactions.export');
Route::get('audit/pdfexport', 'ReportController@auditPdfExport')->name('audit.pdfexport');
Route::get('audit/export', 'ReportController@auditExport')->name('audit.export');
Route::get('/reports/getprocesssteps/{process_id}', 'ProcessController@getSteps');

Route::prefix('graphs')->group(function () {
    Route::get('newclients', 'GraphController@newClients')->name('graphs.newclients');
    Route::get('targetdata', 'GraphController@targetData')->name('graphs.targetdata');
    Route::get('yearlycomparison', 'GraphController@yearlyComparison')->name('graphs.yearlycomparison');
    Route::get('qtrcomparison', 'GraphController@grtCompparison')->name('graphs.qtrcomparison');
    Route::get('gtrfeestotal', 'GraphController@gtrFeesTotal')->name('graphs.gtrfeestotal');

    //Dashboard
    Route::get('getoutstandingactivitiesajax', 'HomeController@getOutstandingActivitiesAjax')->name('graphs.outstandingactivities');
    Route::get('getcompletedclientsajax', 'HomeController@getCompletedClientsAjax')->name('graphs.completedclients');
});

Route::resource('calendarevents', 'CalendarEventController');
Route::get('calendarevents/accept/{id}', 'CalendarEventController@accept')->name('calendarevents.accept');
Route::get('calendarevents/reject/{id}', 'CalendarEventController@reject')->name('calendarevents.reject');

Route::get('locations','LocationController@index')->name('locations.index');
Route::resource('divisions', 'DivisionController');
Route::resource('regions', 'RegionController');
Route::resource('areas', 'AreaController');
Route::resource('offices', 'OfficeController');


Route::get('/users/qausers/{client}', 'UserController@getqausers');
Route::resource('users', 'UserController');
Route::get('users/{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
Route::get('users/{user}/activateuser', 'UserController@activateuser')->name('users.activateuser');


Route::get('insight','InsightController@index')->name('insight.index');

Route::get('configs','ConfigController@index')->name('configs.index');
Route::put('configs','ConfigController@update')->name('configs.update');
Route::get('/get_process_steps/{process_id}','ConfigController@getProcessSteps');
Route::get('/get_process_avg_steps/{process_id}','ConfigController@getProcessAvgSteps');
Route::get('/get_outstanding_step/{process_id}','ConfigController@getOutstandingStep');
Route::get('/get_outstanding_activities/{step_id}','ConfigController@getOutstandingActivities');
Route::get('/get_process_steps_for_ageing/{process_id}','ConfigController@getProcessStepToCalculateAgeFrom');

Route::get('signin', 'AuthController@signin');
Route::get('/authorize', 'AuthController@gettoken');

Route::get('outlook/mail', 'OutlookController@mail')->name('outlook.mail');
Route::get('outlook/calendar', 'OutlookController@calendar')->name('outlook.calendar');


Route::get('activitieslog/{id}', 'LogController@activityLog')->name('activitieslog');

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/check_password/{password}', 'UserController@verifyPassword');

Route::resource('emailtemplates','EmailTemplateController');
Route::get('emailtemplates/create','EmailTemplateController@create')->name('emailtemplates.create');
Route::post('emailtemplates/store','EmailTemplateController@store')->name('emailtemplates.store');
Route::get('emailtemplates/{id}/edit','EmailTemplateController@edit')->name('emailtemplates.edit');
Route::post('emailtemplates/{id}/update','EmailTemplateController@update')->name('emailtemplates.update');
Route::delete('emailtemplates/{id}/destroy','EmailTemplateController@destroy')->name('emailtemplates.destroy');
Route::get('editemail/{id}','EmailTemplateController@ajaxedit');
Route::post('updateemail/{id}','EmailTemplateController@ajaxupdate');
Route::post('getsubject/{id}','EmailTemplateController@getSubject');

Route::resource('emailsignatures','EmailSignatureController');
Route::get('emailsignatures/create','EmailSignatureController@create')->name('emailsignatures.create');
Route::post('emailsignatures/store','EmailSignatureController@store')->name('emailsignatures.store');
Route::get('emailsignatures/{id}/edit','EmailSignatureController@edit')->name('emailsignatures.edit');
Route::post('emailsignatures/{id}/update','EmailSignatureController@update')->name('emailsignatures.update');
Route::delete('emailsignatures/{id}/destroy','EmailSignatureController@destroy')->name('emailsignatures.destroy');

Route::post('/readnotifications','UserController@readNotifications');
Route::post('/readnotificationshistory','UserController@readNotificationsHistory');
Route::post('/markallnotifications','UserController@markAllNotifications');

Route::resource('notifications', 'NotificationHistoryController');
Route::post('/getnotificationscount','UserController@getNotificationsCount');

Route::post('/getqacount','QAController@getQACount');
Route::post('/getqas','QAController@getQAs');
Route::post('/markallqanotifications','QAController@markAllQANotifications');

Route::post('/getmessagecount','MessagesController@getMessageCount');
Route::post('/getmessages','MessagesController@getMessages');

Route::get('search','SearchController@getResults');

Route::resource('relatedparty','RelatedPartyController');
Route::get('relatedparty/{client}/{related_party}/progress','RelatedPartyController@progress')->name('relatedparty.progress');
Route::get('relatedparty/{client}/{related_party}/documents','RelatedPartyController@documents')->name('relatedparty.documents');
Route::get('relatedparty/show/{client_id}', 'RelatedPartyController@related_index')->name('relatedparty.related_index');
Route::post('relatedparty/save/{client_id}/{related_party_id}', 'RelatedPartyController@store');
Route::get('relatedparty/{client_id}/{process_id}/{step_id}/related_party/{related_party_id}', 'RelatedPartyController@stepProgress')->name('relatedparty.stepprogress');
Route::get('relatedparty/{client_id}/{related_party_id}/{process_id}/{step_id}/details', 'RelatedPartyController@show')->name('relatedparty.show');
Route::get('relatedparty/{process_id}/edit/{related_party_id}', 'RelatedPartyController@edit')->name('relatedparty.edit');
Route::post('relatedparty/update/{related_party_id}', 'RelatedPartyController@update')->name('relatedparty.update');
Route::get('relatedparty/activities/{client_id}/{related_party_id}', 'RelatedPartyController@activities')->name('relatedparty.activities');
Route::get('relatedparty/getclient/{client_id}', 'RelatedPartyController@getClient')->name('relatedparty.getclient');
Route::get('relatedparty/addactivities/{client_id}/{process_id}/{step_id}', 'RelatedPartyController@addActivities')->name('relatedparty.addactivities');
Route::post('relatedparty/{client}/sendnotification/{related_party}/{activity?}','RelatedPartyController@sendNotification')->name('relatedparty.sendnotification');
Route::post('relatedparty/{client}/sendtemplate/{related_party}/{activity?}','RelatedPartyController@sendTemplate')->name('relatedparty.sendtemplate');
Route::get('relatedparty/{client}/viewtemplate/{related_party}/{template?}','RelatedPartyController@viewTemplate')->name('relatedparty.viewtemplate');
Route::post('relatedparty/{client}/senddocument/{related_party}/{activity?}','RelatedPartyController@sendDocument')->name('relatedparty.senddocument');
Route::get('relatedparty/{client}/viewdocument/{related_party}/{document?}','RelatedPartyController@viewDocument')->name('relatedparty.viewdocument');
Route::post('relatedparty/{client}/senddocuments/{related_party}/{activity?}','RelatedPartyController@sendDocuments')->name('relatedparty.senddocuments');
Route::post('relatedparty/{client}/{related_party}/storecomment','RelatedPartyController@storeComment')->name('relatedparty.storecomment');
Route::post('relatedparty/{client}/{related_party}/progressing','RelatedPartyController@storeProgressing')->name('relatedparty.progressing');
Route::post('relatedparty/{client}/{related_party}/approval','RelatedPartyController@approval')->name('relatedparty.approval');

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    public function division()
    {
        return $this->belongsTo('App\Division');
    }

    public function areas()
    {
        return $this->hasMany('App\Area');
    }
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Division;
use App\Http\Requests\StoreRegionRequest;
use App\Http\Requests\UpdateRegionRequest;
use App\Region;

class RegionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create()
    {
        return view('regions.create')->with(['divisions' => Division::orderBy('name')->pluck('name', 'id')]);
    }

    public function store(StoreRegionRequest $request)
    {
        $region = new Region;
        $region->name = $request->input('name');
        $region->division_id = $request->input('division');
        $region->save();

        return redirect(route('locations.index'))->with('flash_success', 'Region captured successfully');
    }

    public function edit(Region $region)
    {
        return view('regions.edit')->with(['region' => $region, 'divisions' => Division::orderBy('name')->pluck('name', 'id')]);
    }

    public function update(UpdateRegionRequest $request, Region $region)
    {
        $region->name = $request->input('name');
        $region->division_id = $request->input('division');
        $region->save();

        return redirect(route('locations.index'))->with('flash_success', 'Region updated successfully');
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/regions/create.blade.php
@extends('adminlte.default')

@section('title') Create Region @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('locations.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
    {{Form::open(['url' => route('regions.store'), 'method' => 'post'])}}

    <div class="form-group mt-3">
        {{Form::label('name', 'Name')}}
        {{Form::text('name',old('name'),['class'=>'form-control'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
        @foreach($errors->get('name') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group mt-3">
        {{Form::label('division', 'Division')}}
        {{Form::select('division',$divisions,old('division'),['class'=>'form-control'. ($errors->has('division') ? ' is-invalid' : ''),'placeholder'=>'Please Select'])}}
        @foreach($errors->get('division') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-sm">Save</button>
    </div>

    {{Form::close()}}
    </div>
@endsection

resources/views/regions/edit.blade.php
@extends('adminlte.default')

@section('title') Edit Region @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('locations.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
    {{Form::open(['url' => route('regions.update',$region), 'method' => 'put'])}}

    <div class="form-group mt-3">
        {{Form::label('name', 'Name')}}
        {{Form::text('name',$region->name,['class'=>'form-control'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
        @foreach($errors->get('name') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group mt-3">
        {{Form::label('division', 'Division')}}
        {{Form::select('division',$divisions,$region->division_id,['class'=>'form-control'. ($errors->has('division') ? ' is-invalid' : ''),'placeholder'=>'Please Select'])}}
        @foreach($errors->get('division') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-sm">Update</button>
    </div>

    {{Form::close()}}
    </div>
@endsection