routes/web.php
    Route::get('sla', 'SLAReportController@index')->name('reports.sla');

});

Route::post('reports/productivityreportajax', 'ProductivityReportController@ajaxCall');

Route::get('assigned_actions/{assignedactionid}/delete/{activityid}', 'ActionsController@deleteAssignedAction')->name('assignedactions.delete');
Route::get('assigned_actions/{assignedactionid}/complete/{activityid}', 'ActionsController@completeAssignedAction')->name('assignedactions.complete');
Route::get('assigned_actions/pdfexport', 'ReportController@assignedactivitiesPdfExport')->name('assignedactions.pdfexport');
Route::get('assigned_actions/export', 'ReportController@assignedactivitiesExport')->name('assignedactions.export');
Route::get('audit/pdfexport', 'ReportController@auditPdfExport')->name('audit.pdfexport');
Route::get('audit/export', 'ReportController@auditExport')->name('audit.export');
Route::get('/reports/getprocesssteps/{process_id}', 'ProcessController@getSteps');

Route::prefix('graphs')->group(function () {
    Route::get('newclients', 'GraphController@newClients')->name('graphs.newclients');
    Route::get('targetdata', 'GraphController@targetData')->name('graphs.targetdata');
    Route::get('yearlycomparison', 'GraphController@yearlyComparison')->name('graphs.yearlycomparison');
    Route::get('qtrcomparison', 'GraphController@grtCompparison')->name('graphs.qtrcomparison');
    Route::get('gtrfeestotal', 'GraphController@gtrFeesTotal')->name('graphs.gtrfeestotal');

    //Dashboard
    Route::get('getoutstandingactivitiesajax', 'HomeController@getOutstandingActivitiesAjax')->name('graphs.outstandingactivities');
    Route::get('getcompletedclientsajax', 'HomeController@getCompletedClientsAjax')->name('graphs.completedclients');
});

Route::resource('calendarevents', 'CalendarEventController');
Route::get('calendarevents/accept/{id}', 'CalendarEventController@accept')->name('calendarevents.accept');
Route::get('calendarevents/reject/{id}', 'CalendarEventController@reject')->name('calendarevents.reject');

Route::get('locations','LocationController@index')->name('locations.index');
Route::resource('divisions', 'DivisionController');
Route::resource('regions', 'RegionController');
Route::resource('areas', 'AreaController');
Route::resource('offices', 'OfficeController');


Route::get('/users/qausers/{client}', 'UserController@getqausers');
Route::resource('users', 'UserController');
Route::get('users/{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
Route::get('users/{user}/activateuser', 'UserController@activateuser')->name('users.activateuser');


Route::get('insight','InsightController@index')->name('insight.index');

Route::get('configs','ConfigController@index')->name('configs.index');
Route::put('configs','ConfigController@update')->name('configs.update');
Route::get('/get_process_steps/{process_id}','ConfigController@getProcessSteps');
Route::get('/get_process_avg_steps/{process_id}','ConfigController@getProcessAvgSteps');
Route::get('/get_outstanding_step/{process_id}','ConfigController@getOutstandingStep');
Route::get('/get_outstanding_activities/{step_id}','ConfigController@getOutstandingActivities');
Route::get('/get_process_steps_for_ageing/{process_id}','ConfigController@getProcessStepToCalculateAgeFrom');

Route::get('signin', 'AuthController@signin');
Route::get('/authorize', 'AuthController@gettoken');

Route::get('outlook/mail', 'OutlookController@mail')->name('outlook.mail');
Route::get('outlook/calendar', 'OutlookController@calendar')->name('outlook.calendar');


Route::get('activitieslog/{id}', 'LogController@activityLog')->name('activitieslog');

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/check_password/{password}', 'UserController@verifyPassword');

Route::resource('emailtemplates','EmailTemplateController');
Route::get('emailtemplates/create','EmailTemplateController@create')->name('emailtemplates.create');
Route::post('emailtemplates/store','EmailTemplateController@store')->name('emailtemplates.store');
Route::get('emailtemplates/{id}/edit','EmailTemplateController@edit')->name('emailtemplates.edit');
Route::post('emailtemplates/{id}/update','EmailTemplateController@update')->name('emailtemplates.update');
Route::delete('emailtemplates/{id}/destroy','EmailTemplateController@destroy')->name('emailtemplates.destroy');
Route::get('editemail/{id}','EmailTemplateController@ajaxedit');
Route::post('updateemail/{id}','EmailTemplateController@ajaxupdate');
Route::post('getsubject/{id}','EmailTemplateController@getSubject');

Route::resource('emailsignatures','EmailSignatureController');
Route::get('emailsignatures/create','EmailSignatureController@create')->name('emailsignatures.create');
Route::post('emailsignatures/store','EmailSignatureController@store')->name('emailsignatures.store');
Route::get('emailsignatures/{id}/edit','EmailSignatureController@edit')->name('emailsignatures.edit');
Route::post('emailsignatures/{id}/update','EmailSignatureController@update')->name('emailsignatures.update');
Route::delete('emailsignatures/{id}/destroy','EmailSignatureController@destroy')->name('emailsignatures.destroy');

Route::post('/readnotifications','UserController@readNotifications');
Route::post('/readnotificationshistory','UserController@readNotificationsHistory');
Route::post('/markallnotifications','UserController@markAllNotifications');

Route::resource('notifications', 'NotificationHistoryController');
Route::post('/getnotificationscount','UserController@getNotificationsCount');

Route::post('/getqacount','QAController@getQACount');
Route::post('/getqas','QAController@getQAs');
Route::post('/markallqanotifications','QAController@markAllQANotifications');

Route::post('/getmessagecount','MessagesController@getMessageCount');
Route::post('/getmessages','MessagesController@getMessages');

Route::get('search','SearchController@getResults');

Route::resource('relatedparty','RelatedPartyController');
Route::get('relatedparty/{client}/{related_party}/progress','RelatedPartyController@progress')->name('relatedparty.progress');
Route::get('relatedparty/{client}/{related_party}/documents','RelatedPartyController@documents')->name('relatedparty.documents');
Route::get('relatedparty/show/{client_id}', 'RelatedPartyController@related_index')->name('relatedparty.related_index');
Route::post('relatedparty/save/{client_id}/{related_party_id}', 'RelatedPartyController@store');
Route::get('relatedparty/{client_id}/{process_id}/{step_id}/related_party/{related_party_id}', 'RelatedPartyController@stepProgress')->name('relatedparty.stepprogress');
Route::get('relatedparty/{client_id}/{related_party_id}/{process_id}/{step_id}/details', 'RelatedPartyController@show')->name('relatedparty.show');
Route::get('relatedparty/{process_id}/edit/{related_party_id}', 'RelatedPartyController@edit')->name('relatedparty.edit');
Route::post('relatedparty/update/{related_party_id}', 'RelatedPartyController@update')->name('relatedparty.update');
Route::get('relatedparty/activities/{client_id}/{related_party_id}', 'RelatedPartyController@activities')->name('relatedparty.activities');
Route::get('relatedparty/getclient/{client_id}', 'RelatedPartyController@getClient')->name('relatedparty.getclient');
Route::get('relatedparty/addactivities/{client_id}/{process_id}/{step_id}', 'RelatedPartyController@addActivities')->name('relatedparty.addactivities');
Route::post('relatedparty/{client}/sendnotification/{related_party}/{activity?}','RelatedPartyController@sendNotification')->name('relatedparty.sendnotification');
Route::post('relatedparty/{client}/sendtemplate/{related_party}/{activity?}','RelatedPartyController@sendTemplate')->name('relatedparty.sendtemplate');
Route::get('relatedparty/{client}/viewtemplate/{related_party}/{template?}','RelatedPartyController@viewTemplate')->name('relatedparty.viewtemplate');
Route::post('relatedparty/{client}/senddocument/{related_party}/{activity?}','RelatedPartyController@sendDocument')->name('relatedparty.senddocument');
Route::get('relatedparty/{client}/viewdocument/{related_party}/{document?}','RelatedPartyController@viewDocument')->name('relatedparty.viewdocument');
Route::post('relatedparty/{client}/senddocuments/{related_party}/{activity?}','RelatedPartyController@sendDocuments')->name('relatedparty.senddocuments');
Route::post('relatedparty/{client}/{related_party}/storecomment','RelatedPartyController@storeComment')->name('relatedparty.storecomment');
Route::post('relatedparty/{client}/{related_party}/progressing','RelatedPartyController@storeProgressing')->name('relatedparty.progressing');
Route::post('relatedparty/{client}/{related_party}/approval','RelatedPartyController@approval')->name('relatedparty.approval');
Route::get('relatedparty/{client}/{related_party}/delete','RelatedPartyController@destroy')->name('relatedparty.delete');
Route::get('relatedparty/{clientid}/{related_party}restore','RelatedPartyController@restore')->name('relatedparty.restore');
Route::post('relatedparty/{related_party}/progress/{process?}/{step?}','RelatedPartyController@completeStep')->name('relatedparty.completestep');
Route::post('relatedparty/{related_party}/progress2/{process?}/{step?}','RelatedPartyController@completeStep2')->name('relatedparty.completestep2');
Route::get('/relatedparty/edit/{parent_id}/{related_party}','RelatedPartyController@editRelatedParty');
Route::get('/relatedparty/delete/{parent_id}/{related_party}','RelatedPartyController@deleteRelatedParty');
Route::post('/relatedparty/update/{parent_id}/{related_party}','RelatedPartyController@updateRelatedParty');
Route::post('/relatedparty/link/{parent_id}/{related_party}','RelatedPartyController@linkRelatedParty');
Route::post('/relatedparty/manage/{related_party}','RelatedPartyController@manageRelatedParty');
Route::post('/relatedparty/complete/{related_party}','RelatedPartyController@completeRelatedParty');

app/Http/Controllers/OutlookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Microsoft\Graph\Graph;
use Microsoft\Graph\Model;

class OutlookController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function mail() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }

        $tokenCache = new \App\TokenStore\TokenCache;

        $graph = new Graph();
        $graph->setAccessToken($tokenCache->getAccessToken());

        $user = $graph->createRequest('GET', '/me')
                ->setReturnType(Model\User::class)
                ->execute();

        $messageQueryParams = array(
            // Only return Subject, ReceivedDateTime, and From fields
            "\$select" => "subject,receivedDateTime,from",
            // Sort by ReceivedDateTime, newest first
            "\$orderby" => "receivedDateTime DESC",
            // Return at most 10 results
            "\$top" => "10"
        );

        $getMessagesUrl = '/me/mailfolders/inbox/messages?' . http_build_query($messageQueryParams);
        $messages = $graph->createRequest('GET', $getMessagesUrl)
                ->setReturnType(Model\Message::class)
                ->execute();

        return view('outlook.mail', array(
            'username' => $user->getDisplayName(),
            'messages' => $messages
        ));
    }
    
    public function calendar() {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }

        $tokenCache = new \App\TokenStore\TokenCache;

        $graph = new Graph();
        $graph->setAccessToken($tokenCache->getAccessToken());

        $user = $graph->createRequest('GET', '/me')
                ->setReturnType(Model\User::class)
                ->execute();

        $eventsQueryParams = array(
            // // Only return Subject, Start, and End fields
            "\$select" => "subject,start,end",
            // Sort by Start, oldest first
            "\$orderby" => "Start/DateTime",
            // Return at most 10 results
            "\$top" => "10"
        );

        $getEventsUrl = '/me/events?' . http_build_query($eventsQueryParams);
        $events = $graph->createRequest('GET', $getEventsUrl)
                ->setReturnType(Model\Event::class)
                ->execute();
        
        //dd($events);
        
        return view('outlook.calendar', array(
            'username' => $user->getDisplayName(),
            'events' => $events
        ));
    }

}

resources/views/outlook/calendar.blade.php
@extends('layouts.app')
@section('title') Calendar @endsection
@section('header')
    <h1><i class="fa fa-calendar-o"></i> @yield('title')</h1>
    <button class="btn btn-outline-light float-right" id="blackboard-calendar-event-btn" name="testbutton" data-toggle="modal" data-target="#blackboard-calendar-event-modal"><i class="fa fa-plus"></i> Calendar Event</button>
@endsection
@section('content')
    <hr>
    <div id="calendar">
    </div>
    <div id="blackboard-calendar-event-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title text-left primecolor">Add Calendar Event</h3>
                    <button id="blackboard-modal-close" type="button" class="close" data-dismiss="modal">×</button>
                </div>
                <div class="modal-body" style="overflow: hidden;">
                    <div id="success-msg" class="blackboard-hide">
                        <div class="alert alert-info alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                          <strong>Success!</strong> Calendar event added successfully.
                        </div>
                    </div>
                    <div class="col-md-offset-1 col-md-10">
                        <form method="POST" id="add_calendar_event">
                            {{ csrf_field() }}
                            <div class="form-group has-feedback">
                                <input type="text" id="title" name="title" value="{{ old('title') }}" class="form-control" placeholder="Title">
                                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                <span class="text-danger">
                                    <strong id="title-error"></strong>
                                </span>
                            </div>
                            <div class="form-group has-feedback">
                                <input type="text" id="start_date" name="start_date" value="{{ date("Y-m-d H:i:s") }}" class="form-control" placeholder="Start Date">
                                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                <span class="text-danger">
                                    <strong id="start-date-error"></strong>
                                </span>
                            </div>
                            <div class="form-group has-feedback">
                                <input type="text" id="end_date" name="end_date" value="{{ date("Y-m-d 23:59:59") }}" class="form-control" placeholder="End Date">
                                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                <span class="text-danger">
                                    <strong id="end-date-error"></strong>
                                </span>
                            </div>
                            <div class="form-group has-feedback">
                                <input type="email" id="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="Email">
                                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                <span class="text-danger">
                                    <strong id="email-error"></strong>
                                </span>
                            </div>
                            <div class="form-group">
                                <button type="button" id="submitbtn" name="submitbtn" class="btn btn-primary btn-prime white btn-flat" onclick="storeEvent();">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('extra-css')
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css'/>
    <style>
        .blackboard-hide{
            display: none;
        }
    </style>
@endsection
@section('extra-js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>
    <script>
        $(document).ready(function() {
            
            calendar = $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'listDay,month,agendaWeek,agendaDay'
                },
                editable: true,
                events: [
                @foreach($events as $event)
                {
                    id : '{!! $event->getId() !!}',
                    title  : '{!! $event->getSubject() !!}',
                    start  : '{!! (new DateTime($event->getStart()->getDateTime()))->format(DATE_RFC2822) !!}',
                    end    : '{!! (new DateTime($event->getEnd()->getDateTime()))->format(DATE_RFC822) !!}'
                },
                @endforeach
                ],
                selectable: true,
                selectHelper: true,
                select: function (start, end, allDay) {
                    $("#start_date").val($.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss"));
                    $("#end_date").val($.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss"));
                    $("#blackboard-calendar-event-btn").click();
                    calendar.fullCalendar('unselect');
                },
                editable: true,
                eventDrop: function (event, delta) {
                            var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
                            var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
                            $.ajax({
                                url: 'edit-event.php',
                                data: 'title=' + event.title + '&start=' + start + '&end=' + end + '&id=' + event.id,
                                type: "POST",
                                success: function (response) {
                                    displayMessage("Updated Successfully");
                                }
                            });
                        },
                eventClick: function (event) {
                    var deleteMsg = confirm("Do you really want to delete?");
                    if (deleteMsg) {
                        axios.delete('{!!url('calendarevents')!!}/'+event.id )
                        .then(function (response) {
                            alert(response.data.success);
                            $('#calendar').fullCalendar('removeEvents', event._id);
                        })
                        .catch(function () {
                            alert("Error: There was a problem with this request.");
                        });
                    }
                }
            })

        });
        
        function storeEvent(){
            //Clear form errors
            $('#title-error').html("");
            $('#email-error').html("");
            $('#start-date-error').html("");
            $('#end-date-error').html("");
            $('#submitbtn').html("Processing ...");
            $("#submitbtn").attr("disabled", "disabled");
            
            var post_data = {
                title: $("#title").val(),
                email: $("#email").val(),
                start_date: $("#start_date").val(),
                end_date: $("#end_date").val()
            };
            
            axios.post('{{route('calendarevents.store')}}', post_data)
            .then(function (response) {
                
                if(response.data.errors) {
                    if(response.data.errors.title){
                        $( '#title-error' ).html( response.data.errors.title[0] );
                    }
                    if(response.data.errors.email){
                        $( '#email-error' ).html( response.data.errors.email[0] );
                    }
                    if(response.data.errors.password){
                        $( '#start-date-error' ).html( data.errors.start_date[0] );
                    }
                    if(response.data.errors.password){
                        $( '#end-date-error' ).html( data.errors.end_date[0] );
                    }
                }
                if(response.data.success) {
                    $('#success-msg').removeClass('blackboard-hide');
                    $( '#title' ).val("");
                    $( '#email' ).val("");
                    $( '#start_date' ).val("");
                    $( '#end_date' ).val("");
            
                    setTimeout(function() {
                        $("#blackboard-modal-close").click();
                        $('#success-msg').addClass('blackboard-hide');
                    }, 3000);
                    
                    calendar.fullCalendar('renderEvent',
                        {
                            id: response.data.id,
                            title: response.data.title,
                            start: response.data.start_date,
                            end: response.data.end_date,
                            allDay: false
                        },
                        true
                    );
                }
                enableSubmitBtn();
            })
            .catch(function () {
                alert("Error: There was a problem with this request.");
                enableSubmitBtn();
            });
            
        }
        
        function enableSubmitBtn(){
            $('#submitbtn').html("Submit");
            $("#submitbtn").removeAttr("disabled", "disabled");
        }
    </script>
@endsection

resources/views/outlook/index.blade.php
@extends('layouts.app')
@section('title') Outlook Calendar @endsection
@section('header')
    <h1><i class="fa fa-calendar-o"></i> @yield('title')</h1>
@endsection
@section('content')
<div id="inbox" class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title">Calendar</h1>
    </div>
    <div class="panel-body">
        Here are the 10 oldest events in your calendar.
    </div>
    <div class="list-group">
        <?php if (isset($events)) {
            foreach ($events as $event) {
                ?>
                <div class="list-group-item">
                    <h3 class="list-group-item-heading"><?php echo $event->getSubject() ?></h3>
                    <p class="list-group-item-heading text-muted">Start: <?php echo (new DateTime($event->getStart()->getDateTime()))->format(DATE_RFC2822) ?></p>
                    <p class="list-group-item-heading text-muted">End: <?php echo (new DateTime($event->getEnd()->getDateTime()))->format(DATE_RFC822) ?></p>
                </div>
            <?php }
        }
        ?>
    </div>
</div>
@endsection

resources/views/outlook/mail.blade.php
@extends('layouts.app')
@section('title') Outlook Mail @endsection
@section('header')
    <h1><i class="fa fa-calendar-o"></i> @yield('title')</h1>
@endsection
@section('content')
<div id="inbox" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Inbox</h1>
  </div>
  <div class="panel-body">
    Here are the 10 most recent messages in your inbox.
  </div>
  <div class="list-group">
    <?php if (isset($messages)) {
      foreach($messages as $message) { ?>
    <div class="list-group-item">
      <h3 class="list-group-item-heading"><?php echo $message->getSubject() ?></h3>
      <h4 class="list-group-item-heading"><?php echo $message->getFrom()->getEmailAddress()->getName() ?></h4>
      <p class="list-group-item-heading text-muted"><em>Received: <?php echo $message->getReceivedDateTime()->format(DATE_RFC2822) ?></em></p>
    </div>
    <?php  }
    } ?>
  </div>
</div>
@endsection