routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('login');
})->name('home');

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::get('create/{client_id}/{related_party_id}', ['as' => 'messages.relatedparty', 'uses' => 'MessagesController@relatedparty_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::any('/', 'HomeController@index')->name('home');
Route::any('/home', 'HomeController@index');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::any('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::get('clients/xlsexport','ClientController@xlsExport')->name('clients.xlsexport');
Route::resource('clients', 'ClientController');

Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{process}/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents/{process}/{step}','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/edit/{process}/{step}','ClientController@edit')->name('clients.edit');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');
Route::get('clients/{client}/activityprogress/{process}/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
Route::post('clients/{client}/qa','ClientController@storeQA')->name('clients.qa');
Route::post('clients/{client}/qacomplete','ClientController@completeQA')->name('clients.qacomplete');
Route::post('clients/{client}/qaprod','ClientController@storeProd')->name('clients.qaprod');
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');
Route::get('clients/{clientid}/show/{process}/{step}','ClientController@show')->name('clients.show');
Route::get('clients/{clientid}/restore','ClientController@restore')->name('clients.restore');
Route::post('clients/{clientid}/addcomment/{activityid}','ActivityCommentController@addComment');
Route::post('clients/{clientid}/showcomment/{activityid}','ActivityCommentController@showComment');
Route::post('clients/deletecomment/{commentid}','ActivityCommentController@destroyComment');
Route::post('clients/editcomment/{commentid}','ActivityCommentController@editComment');
Route::post('clients/updatecomment/{commentid}','ActivityCommentController@updateComment');
Route::get('client/{client}/basket/{process}/{step}', 'ClientBasketController@show')->name('client.basket');
Route::any('client/{client}/progress/{process}/{step}', 'ClientBasketController@clientProgress')->name('client.progress');
Route::post('client/{client}/storeprogress/{process}/{step}', 'ClientBasketController@clientStoreProgress')->name('client.storeprogress');
Route::post('client/{client}/sendclientemail', 'ClientBasketController@sendClientEmail');

Route::get('activity/include-in-basket', 'ClientBasketController@includeActivityInClientBasket')->name('basket.include');
Route::get('forms/include-in-basket', 'FormsController@includeInputInClientBasket');

Route::get('clients/{client}/actions','ClientController@actions')->name('clients.actions');

app/ClientForm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ClientForm extends Model
{
    protected $table = 'client_forms';
    protected $touches = ['client'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return pathinfo($this->file, PATHINFO_EXTENSION);
    }

    public function size()
    {
        try {
            $bytes = Storage::size('crf/' . $this->file);
            $i = floor(log($bytes, 1024));
            return round($bytes / pow(1024, $i), [0, 0, 2, 2, 3][$i]) . ['B', 'kB', 'MB', 'GB', 'TB'][$i];
        } catch (\Exception $e) {
            return "LStat";
        }
    }

    public function client()
    {
        return $this->belongsTo('App\Client','client_id');
    }
}

resources/views/clients/amlreports.blade.php
@extends('layouts.app')

@section('title') Clients @endsection

@section('header')
    <h1><i class="fa fa-address-card-o"></i> @yield('title')</h1>
    <a href="{{route('clients.create')}}" class="btn btn-outline-light float-right"><i class="fa fa-plus"></i> Client</a>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not completed','yes'=>'Completed'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',$steps ,old('step'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-outline-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Process</th>
                <th>Created</th>
                <th>Completed</th>
                <th><abbr title="Days taken to complete a clients process.">Duration</abbr></th>
                <th>Step</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client)}}">{{$client->company}}</a></td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->contact}}</td>
                    <td>{{$client->process->name}}</td>
                    <td>{{$client->created_at}}</td>
                    <td>{{!is_null($client->completed_at) ? $client->completed_at->toDateString() : ''}}</td>
                    <td>{{$client->completed_days}}</td>
                    <td>{{$client->getCurrentStep()->name}}</td>
                    <td><a href="{{route('profile',$client->introducer)}}" title="{{$client->introducer->name()}}"><img src="{{route('avatar',['q'=>$client->introducer->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>

    <small class="text-muted">Found <b>{{sizeof($clients)}}</b> clients matching those criteria.</small>
@endsection

resources/views/clients/edit.blade.php
@extends('adminlte.default')

@section('title') Update Client @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('clients.show',[$client,$process_id,$step['id']])}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <nav class="tabbable">
            <div class="nav nav-tabs">
                <a class="nav-link active show" id="default-tab" data-toggle="tab" href="#default" role="tab" aria-controls="default" aria-selected="false">Default</a>
                @foreach($forms as $key =>$value)
                    @foreach($value as $section =>$v1)
                        <a class="nav-link" id="{{strtolower(str_replace(' ','_',$section))}}-tab" data-toggle="tab" href="#{{strtolower(str_replace(' ','_',$section))}}" role="tab" aria-controls="{{strtolower(str_replace(' ','_',$section))}}" aria-selected="true">{{$section}}</a>
                    @endforeach
                @endforeach
            </div>
        </nav>
        {{Form::open(['url' => route('clients.update', $client), 'method' => 'pUt','autocomplete'=>'off'])}}
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active p-3" id="default" role="tabpanel" aria-labelledby="default-tab">

    <div class="form-group mt-3">
        {{Form::label('process', 'Process')}}
        {{Form::select('process',$processes,$client->process_id,['class'=>'form-control form-control-sm'. ($errors->has('process') ? ' is-invalid' : ''),'autofocus','id'=>'process'])}}
        @foreach($errors->get('process') as $error)
            <div class="invalid-feedback">
                {{$error}}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('first_name', 'First Names')}}
        {{Form::text('first_name',$client->first_name,['class'=>'form-control form-control-sm'. ($errors->has('first_name') ? ' is-invalid' : ''),'placeholder'=>'First Name'])}}
        @foreach($errors->get('first_name') as $error)
            <div class="invalid-feedback">
                {{$error}}
            </div>
        @endforeach
    </div>

        <div class="form-group">
            {{Form::label('last_name', 'Surname')}}
            {{Form::text('last_name',$client->last_name,['class'=>'form-control form-control-sm'. ($errors->has('last_name') ? ' is-invalid' : ''),'placeholder'=>'Last Name'])}}
            @foreach($errors->get('last_name') as $error)
                <div class="invalid-feedback">
                    {{$error}}
                </div>
            @endforeach
        </div>

        <div class="form-group">
            {{Form::label('initials', 'Initials')}}
            {{Form::text('initials',$client->initials,['class'=>'form-control form-control-sm'. ($errors->has('last_name') ? ' is-invalid' : ''),'placeholder'=>'Initials'])}}
            @foreach($errors->get('initials') as $error)
                <div class="invalid-feedback">
                    {{$error}}
                </div>
            @endforeach
        </div>

    <div class="form-group">
        {{Form::label('id_number', 'ID/Passport Number')}}
        {{Form::text('id_number',$client->id_number,['class'=>'form-control form-control-sm'. ($errors->has('id_number') ? ' is-invalid' : ''),'placeholder'=>'ID Number', 'id'=>'id_number'])}}
        @foreach($errors->get('id_number') as $error)
            <div class="invalid-feedback">
                {{$error}}
            </div>
        @endforeach
        <div class="row pt-3" id="hide-smart-id" style="display: {{isset($client->id_number)?'flex':'none'}}">
            <div class="col-md-3"><strong>Date of Birth: </strong>{{$date_of_birth}}</div>
            <div class="col-md-3"><strong>Gender: </strong>{{$gender}}</div>
            <div class="col-md-3"><strong>Citizenship: </strong>{{$citizenship}}</div>
        </div>
    </div>

        <div class="form-group">
            {{Form::label('email', 'Email')}}
            {{Form::email('email',$client->email,['class'=>'form-control form-control-sm'. ($errors->has('email') ? ' is-invalid' : ''),'placeholder'=>'Email'])}}
            @foreach($errors->get('email') as $error)
                <div class="invalid-feedback">
                    {{$error}}
                </div>
            @endforeach
        </div>

        <div class="form-group">
            {{Form::label('contact', 'Cellphone Number')}}
            {{Form::text('contact',$client->contact,['class'=>'form-control form-control-sm'. ($errors->has('contact') ? ' is-invalid' : ''),'placeholder'=>'Contact Number'])}}
            @foreach($errors->get('contact') as $error)
                <div class="invalid-feedback">
                    {{$error}}
                </div>
            @endforeach
        </div>
    </div>
    @foreach($forms as $key =>$value)
        @foreach($value as $section =>$v1)
            <div class="tab-pane fade p-3" id="{{strtolower(str_replace(' ','_',$section))}}" role="tabpanel" aria-labelledby="{{strtolower(str_replace(' ','_',$section))}}-tab">
                @foreach($v1 as $k1 =>$inputs)

                    @foreach($inputs["inputs"] as $input)
                        @if($input['type'] == 'dropdown')
                            @php

                                $arr = (array)$input['dropdown_items'];
                                $arr2 = (array)$input['dropdown_values'];

                            @endphp
                            <input type="hidden" id="old_{{$input['id']}}" name="old_{{$input['id']}}" value="{{(!empty($arr2) ? implode(',',$arr2) : old($input['id']))}}">
                        @else
                            <input type="hidden" id="old_{{$input['id']}}" name="old_{{$input['id']}}" value="{{old($input['id'])}}">
                        @endif
                        <div class="col-lg-12">
                            <div class="form-group">
                                {{Form::label(strtolower(str_replace($input['name'],' ','_')), $input["name"])}}
                                @if($input['type']=='text')
                                    {{Form::text($input['id'],(isset($input['value'])?$input['value']:old($input['id'])),['class'=>'form-control form-control-sm','placeholder'=>'Insert text...','spellcheck'=>'true'])}}
                                @endif

                                @if($input['type']=='date')
                                    <input name="{{$input['id']}}" type="date" min="1900-01-01" max="2030-12-30" value="{{(isset($input['value'])?$input['value']:old($input['id']))}}" class="form-control form-control-sm" placeholder="Insert date..." />
                                @endif

                                @if($input['type']=='textarea')
                                    <textarea spellcheck="true" rows="5" name="{{$input['id']}}" class="form-control form-control-sm text-area">{{(isset($input['value'])?$input['value']:old($input['id']))}}</textarea>
                                @endif

                                @if($input['type']=='boolean')
                                    {{Form::select($input['id'],[1=>'Yes',0=>'No'],(isset($input['value'])?$input['value']:old($input['id'])),['class'=>'form-control form-control-sm','placeholder'=>'Please select...'])}}
                                @endif
                                @if($input['type']=='dropdown')

                                    <select multiple="multiple" id="{{$input['id']}}" name="{{$input["id"]}}[]" class="form-control form-control-sm chosen-select">
                                        @php
                                            foreach((array) $arr as $key => $value){
                                                echo '<option value="'.$key.'" '.(in_array($key,$arr2) ? 'selected' : '').'>'.$value.'</option>';
                                            }
                                        @endphp
                                    </select>
                                    <div>
                                        <small class="form-text text-muted">
                                            Search and select multiple entries
                                        </small>
                                    </div>

                                @endif
                            </div>
                        </div>
                    @endforeach
                @endforeach
            </div>
            @endforeach
            @endforeach

            </div>
            <div class="blackboard-fab mr-3 mb-3">
                <button type="submit" class="btn btn-info btn-lg"><i class="fa fa-save"></i><span style="font-size:1rem;line-height: 1.8;padding-left:10px;float: right;display:block;text-align:left;">Save</span></button>
            </div>
            {{Form::close()}}
    </div>
    <div class="modal fade" id="modalProcess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center" style="border-bottom: 0px;padding:.5rem;">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3">
                    <div class="row">
                        <div class="md-form col-sm-12 mb-3 text-left message">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('extra-css')
    <link rel="stylesheet" href="{{asset('chosen/chosen.min.css')}}">
    <style>
        a:focus{
            outline:none !important;
            border:0px !important;
        }

        .activity a{
            color: rgba(0,0,0,0.5) !important;
        }

        .activity a.dropdown-item {
            color:#212529 !important;
        }

        .btn-comment{
            padding: .25rem .25rem;
            font-size: .575rem;
            line-height: 1;
            border-radius: .2rem;
        }

        .modal-dialog {
            max-width: 700px;
            margin: 1.75rem auto;
            min-width: 500px;
        }

        .chosen-container, .chosen-container-multi{
            width:100% !important;
        }

        .chosen-container, .chosen-container-multi{
            line-height: 30px;
        }

        .modal-open .modal{
            padding-right: 0px !important;
        }

        .progress { position:relative; width:100%; border: 1px solid #7F98B2; padding: 1px; border-radius: 3px; display:none; }
        .bar { background-color: #B4F5B4; width:0%; height:25px; border-radius: 3px; }
        .percent { position:absolute; display:inline-block; top:3px; left:48%; color: #7F98B2;}
    </style>
@endsection
@section('extra-js')
    <script>
        $(function () {
            $("#id_number").on('blur', function () {
                let id_number = $(this).val().replace('-', '').replace(" ", '').replace('\\', '').replace('/', '');
                let partial_d_o_b = id_number.substring(0,2)+'-'+ id_number.substring(2,4) + '-' + id_number.substring(4,6);
                let date_of_birth = ((id_number.substring(0,2) > 45) && (id_number.substring(0,2) <= 99)) ? '19' + partial_d_o_b : '20' + partial_d_o_b;

                let gender = "";
                if (id_number.substring(6, 10) < 5000){
                    gender = "Female";
                }else if(id_number.substring(6, 10) >= 5000){
                    gender = "Male";
                }

                let citizenship = (id_number.substring(10, 11) == 0)?"SA Citizen":"Permanent Resident";

                $("#hide-smart-id").show().html('' +
                    '<div class="col-md-3"><strong>Date of Birth: </strong>' + date_of_birth + '</div>' +
                    '<div class="col-md-3"><strong>Gender: </strong>' + gender + '</div>' +
                    '<div class="col-md-3"><strong>Citizenship: </strong>' + citizenship + '</div>'
                );
            });
        })
        $(function(){
            $('#process').on('change',function(){
                $.ajax({
                    dataType: 'json',
                    url: '/processes/step_count/'+$('#process').val(),
                    type:'GET'
                }).done(function(data) {
                    if(data === 0){
                        let process = $('#process').val();
                        $('#modalProcess').modal('show');
                        $('#modalProcess').find('.message').html('The process you selected currently has no steps.<br /><br />' +
                            'Click <a href="/processes/' + process + '/show">here</a> to add steps to this process now.');
                        $('body').find('.update-client').prop('disabled',true);
                    } else {
                        $('body').find('.update-client').prop('disabled',false);
                    }
                });
            })

            let projects = [@foreach($project as $autocomplete_project) {!! '"'.$autocomplete_project->name.'",' !!} @endforeach];

            autocomplete(document.getElementById("project"), projects);

            $('#project').on('change', function () {
                if ($(this).val() =='{{$projects_down_down->keys()->last()}}'){
                    $(this).remove();
                    $('#project-wraper').append(
                        '<input type="text" name="project_new" class="form-control form-control-sm">'
                    );
                }
            })

        })
    </script>
@endsection

resources/views/clients/show.blade.php
@extends('adminlte.default')

@section('title') {{($client->company == '' || $client->company == 'N/A' || $client->company == 'n/a' ? $client->first_name.' '.$client->last_name : $client->company )}} @endsection

@section('header')
    <div class="container-fluid container-title form-inline">
        <div class="col-sm-4">
            <h3 class="form-inline">@yield('title')</h3>
        </div>
        @auth
        <div class="col-sm-4 process-dropdown">
        @if(isset($view_process_dropdown) && isset($client))
                <input type="hidden" value="{{$client->id}}" id="client_id" />
                <label class="float-left">View Process</label> <select class="form-control form-control-sm float-left ml-3" id="viewprocess">
                @forelse($view_process_dropdown as $processdd)
                    <option value="{{$processdd['id']}}" {{(isset($process_id) && $process_id == $processdd['id'] ? 'selected' : '')}}>{{$processdd['name']}}</option>
                @empty
                    <option value="">There are no processes assigned for this client.</option>
                @endforelse
            </select>
        @else
            @forelse(auth()->user()->office()->processes->first()->steps as $step)
                <div class="col-lg blackboard-step-{{$step->id}}">
                    {{$step->name}}
                </div>
            @empty
                <p>There are no processes assigned for this client.</p>
            @endforelse
        @endif
        </div>
        <div class="col-sm-4 back-btn">
        <a href="{{(isset($path) && $path == 1 ? $path_route : route('clients.index'))}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
        </div>
        @endauth
    </div>
@endsection

@section('content')
<div class="container-fluid" style="padding-top: 20px;">
    @include('clients.process')

    <ul class="nav nav-tabs nav-fill mt-3">
        <li class="nav-item">
            <a class="nav-link {{active('clients.show','active')}}" href="{{route('clients.show',[$client,$process_id,$step["id"]])}}">Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{(\Request::is('clients/*/progress/*') ? 'active' : '')}}" href="{{route('clients.progress',$client)}}/{{$process_id}}/{{$step["id"]}}">Progress</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{active('clients.documents','active')}}" href="{{route('clients.documents',[$client,$process_id,$step["id"]])}}">Documents</a>
        </li>
            <li class="nav-item">
                <a class="nav-link {{active('client.basket','active') || active('client.progress','active')}}" href="{{route('client.basket',[$client,$process_id,$step["id"]])}}">Client Basket</a>
            </li>
</ul>

<div class="row m-0 pt-3 pb-5 border border-top-0 activity-container">

@yield('tab-content')
</div>
</div>
@endsection